(() => {
  const root=document.querySelector('.guide'); if(!root)return;
  const booking='https://calendly.com/deanfernandes/30min';
  const entries=[
    {id:'leadership',title:'Fractional & interim leadership',url:'/leadership.html',keys:/fractional|interim|leadership|vacancy|transition|part.time/i,text:'NorthRidge offers fractional and interim executive leadership for a defined mandate, a transition, or an ongoing role. Fractional leadership adds executive capacity on an ongoing basis; interim leadership supports a temporary leadership need. Would you like to explore the approach or discuss your situation?'},
    {id:'executive',title:'Executive experience',url:'/executive.html',keys:/hiring|hire|full.time|cto|cio|resume|cv|executive role/i,text:'Dean brings more than 25 years of technology and product leadership across NWN, DXC Technology, Pearson and Nortel. For a full-time executive opportunity, explore his experience or share the role through the contact form.'},
    {id:'ai',title:'AI & transformation advisory',url:'/ai-transformation.html',keys:/\bai\b|artificial|moderni|transform|automation|consulting|strategy/i,text:'Dean helps organizations turn AI and modernization initiatives into an owned, measurable agenda, connecting technology, products and teams with business priorities. What are you looking to change: your technology direction, delivery, or leadership capacity?'},
    {id:'board',title:'Board opportunities',url:'/board.html',keys:/board|governance|due diligence/i,text:'NorthRidge welcomes board and advisory inquiries. The board page outlines Dean’s perspective; use the contact form to describe the organization and the opportunity.'},
    {id:'results',title:'Results & case studies',url:'/results.html',keys:/results|case stud|track record|achieve|outcome|experience/i,text:'The site highlights Dean’s prior executive work: contributions to more than $300M in revenue growth at NWN, a $2B workplace portfolio at DXC, and a global workplace program at Pearson. These are examples from prior roles, not promises of future results.'},
    {id:'partners',title:'Partner ecosystem',url:'/partners.html',keys:/partner|ecosystem|genesys|five9|dell|lenovo|microsoft|cisco|aws/i,text:'The partner ecosystem page brings together the technology relationships and specialists relevant to NorthRidge’s work. Explore that page, or ask Dean which resources fit your engagement.'},
    {id:'insights',title:'Insights',url:'/insights.html',keys:/insight|article|media|read|resource/i,text:'You can find Dean’s published perspectives and selected commentary on AI, infrastructure and transformation in Insights.'},
    {id:'about',title:'About Dean',url:'/#about',keys:/who|about|background|dean|location|where|remote|onsite|on.site/i,text:'Dean Fernandes is the founder of NorthRidge Advisory, based in Manalapan, New Jersey. Remote and on-site participation is agreed around the role or engagement. His background spans technology leadership, product portfolios and global transformation.'},
    {id:'privacy',title:'Privacy information',url:'/privacy.html',keys:/privacy|personal data|confidential|store|retain/i,text:'The contact form uses your details to respond to your inquiry. This assistant provides prepared website guidance, and its conversation stays on this page until you refresh or leave. Please use the privacy page for the site’s published policy.'}
  ];
  root.innerHTML=`<button class="nr-launch" aria-controls="nr-chat" aria-expanded="false"><img src="/assistant-logo.png" alt=""><span>Ask NorthRidge<small>Services · questions · booking</small></span></button><section id="nr-chat" class="nr-chat" role="dialog" aria-modal="false" aria-labelledby="nr-chat-title" hidden><header class="nr-chat-head"><img src="/assistant-logo.png" alt="NorthRidge logo"><div><strong id="nr-chat-title">NorthRidge Assistant</strong><small>Your website & service guide</small></div><button class="nr-close" aria-label="Close assistant">×</button></header><div class="nr-messages" role="log" aria-live="polite" aria-relevant="additions text"></div><div class="nr-suggestions" aria-label="Suggested questions"></div><form class="nr-compose"><label class="nr-sr" for="nr-question">Ask NorthRidge a question</label><input id="nr-question" maxlength="500" required placeholder="What can I help you find?" autocomplete="off"><button type="submit">Send</button></form><footer class="nr-chat-note">Website guidance · No live availability or pricing</footer></section>`;
  const launch=root.querySelector('.nr-launch'),chat=root.querySelector('.nr-chat'),log=root.querySelector('.nr-messages'),input=root.querySelector('input'),suggestions=root.querySelector('.nr-suggestions');
  let last=null;
  function close(){chat.hidden=true;launch.setAttribute('aria-expanded','false');launch.focus();}
  launch.addEventListener('click',()=>{chat.hidden=!chat.hidden;launch.setAttribute('aria-expanded',String(!chat.hidden));if(!chat.hidden)input.focus();});
  root.querySelector('.nr-close').addEventListener('click',close);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!chat.hidden)close();});
  function message(text,who='assistant',links=[]){const item=document.createElement('div');item.className='nr-message '+who;const p=document.createElement('p');p.textContent=text;item.append(p);links.forEach(([label,url])=>{const a=document.createElement('a');a.textContent=label+' →';a.href=url;if(url.startsWith('https:')){a.target='_blank';a.rel='noopener';}else a.addEventListener('click',()=>{close();});item.append(a);});log.append(item);log.scrollTop=log.scrollHeight;}
  function chips(labels){suggestions.replaceChildren();labels.forEach(label=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>respond(label));suggestions.append(b);});}
  const contact=['Contact Dean','/#contact'],book=['Choose a meeting time',booking];
  function respond(raw){const q=raw.trim();if(!q)return;message(q,'user');input.value='';
    if(/\b(price|prices|pricing|cost|costs|fee|fees|rate|rates|charge|retainer|budget|quote)\b/i.test(q)){message('Pricing depends on the scope and engagement. The site does not publish a fixed rate. Share your goals and timing with Dean to discuss a quote'+(last?' for '+last.title.toLowerCase():'')+'.','assistant',[contact,book]);chips(['Book a meeting','Explore services']);return;}
    if(/book|schedule|availability|available|meeting|zoom|appointment|consultation/i.test(q)){message('You can book a 30-minute consultation through Calendly. It shows available times and the meeting location before you confirm. I can take you there, but I cannot reserve a time inside this chat.','assistant',[book,contact]);chips(['Contact Dean','Explore services']);return;}
    if(/contact|email|phone|reach|speak|human/i.test(q)){message('Send Dean a note at dean@northridgeadvisory.net or use the contact form. Include your goals and timing; company and phone are optional.','assistant',[contact,book]);chips(['Book a meeting','Explore services']);return;}
    if(/all pages|navigate|site map|everything/i.test(q)){message('Here are the main areas of the website. Which would you like to explore?','assistant',[['Homepage','/'],...entries.map(e=>[e.title,e.url]),contact,book]);chips(['Explore services','Pricing','Book a meeting']);return;}
    if(/explore services|what.*(offer|do)|help me|not sure|start/i.test(q)){message('Are you hiring a full-time executive, looking for fractional or interim leadership, or planning a technology transformation? Choose a starting point and I’ll guide you.','assistant');chips(['Hiring an executive','Fractional leadership','AI transformation','All pages']);return;}
    if(/^(hi|hello|hey|thanks|thank you)[!. ]*$/i.test(q)){message(/thank/i.test(q)?'You’re welcome. What else would you like to explore?':'Hello! I can help you explore NorthRidge, find answers, or book time with Dean. What brings you here?');chips(['Explore services','All pages','Book a meeting']);return;}
    const entry=entries.find(e=>e.keys.test(q))||(/more|that|this|how.*work|next|yes|detail/i.test(q)?last:null);
    if(entry){last=entry;message(entry.text,'assistant',[[entry.title,entry.url],contact]);chips(['Tell me more','What does it cost?','Book a meeting']);return;}
    message('I don’t have a published answer to that question. I can guide you through the site, or you can ask Dean directly for a precise answer.','assistant',[contact]);chips(['All pages','Explore services','Book a meeting']);
  }
  root.querySelector('form').addEventListener('submit',e=>{e.preventDefault();respond(input.value);input.focus();});
  message('Hello, welcome to NorthRidge. Are you looking for executive leadership, help with a business challenge, or a conversation with Dean?');chips(['Explore services','Pricing','Book a meeting','All pages']);
  const navigation=document.querySelector('.navlinks');if(navigation&&!navigation.querySelector('a[href*="calendly.com"]')){const a=document.createElement('a');a.href=booking;a.textContent='Book a consultation';a.target='_blank';a.rel='noopener';navigation.append(a);}
})();
